version: "3.8"

services:
  carxpress-db:
    image: postgres
    restart: always
    container_name: "carxpress-db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: laputaama
      POSTGRES_DB: carxpress
    ports:
      - "5433:5432"

    volumes:
      - ./db-postgres/postgres-data:/var/lib/postgresql/data
      - ./db-postgres/create.sql:/docker-entrypoint-initdb.d/create.sql
    networks:
      - carxpress-net

  carxpress-app:
    image: "martina337/carxpress-app:2.0"
    container_name: carxpress_app
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url"  : "jdbc:postgresql://carxpress-db:5433/carxpress",
             "spring.datasource.username" : "postgres",
             "spring.datasource.password" : "laputaama",
             "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
             "spring.jpa.hibernate.ddl-auto" : "validate"
           }'
    depends_on:
      - carxpress-db
    ports:
      - "8080:8080"
    networks:
      - carxpress-net


networks:
  carxpress-net:
    driver: bridge

volumes:
  postgres-data:
